apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: memcached-profile
  name: memcached-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memcached-profile
  strategy: {}
  template:
    metadata:
      annotations:
        sidecar.istio.io/statsHistogramBuckets: '{"istiocustom":[50,100,200,500,1000,2500,5000,10000]}'
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: memcached-profile
    spec:
      containers:
        - env:
            - name: MEMCACHED_CACHE_SIZE
              value: "128"
            - name: MEMCACHED_THREADS
              value: "2"
          image: ##########/memcached
          name: profile-mmc
          ports:
            - containerPort: 11211
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
      imagePullSecrets:
        - name: ##########
      restartPolicy: Always
status: {}
