---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "webui-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "teastore-webui"
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "persistence-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "teastore-persistence"
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "auth-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "teastore-auth"
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "image-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "teastore-image"
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: "recommender-autoscaler"
  namespace: "default"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "teastore-recommender"
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
